// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receipt.WebApi.Data;

#nullable disable

namespace Receipt.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240607165317_initial-with-adding-Item-Entity")]
    partial class initialwithaddingItemEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Receipt.WebApi.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InStock = 100,
                            Name = "Apple",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            InStock = 150,
                            Name = "Banana",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 3,
                            InStock = 200,
                            Name = "Orange",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 4,
                            InStock = 50,
                            Name = "Milk",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 5,
                            InStock = 80,
                            Name = "Bread",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 6,
                            InStock = 60,
                            Name = "Butter",
                            Price = 1.75m
                        },
                        new
                        {
                            Id = 7,
                            InStock = 40,
                            Name = "Cheese",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 8,
                            InStock = 30,
                            Name = "Chicken Breast",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 9,
                            InStock = 25,
                            Name = "Ground Beef",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 10,
                            InStock = 90,
                            Name = "Eggs",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 11,
                            InStock = 120,
                            Name = "Rice",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = 12,
                            InStock = 100,
                            Name = "Pasta",
                            Price = 1.10m
                        },
                        new
                        {
                            Id = 13,
                            InStock = 200,
                            Name = "Tomato",
                            Price = 0.90m
                        },
                        new
                        {
                            Id = 14,
                            InStock = 75,
                            Name = "Lettuce",
                            Price = 1.20m
                        },
                        new
                        {
                            Id = 15,
                            InStock = 180,
                            Name = "Carrot",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = 16,
                            InStock = 150,
                            Name = "Potato",
                            Price = 0.70m
                        },
                        new
                        {
                            Id = 17,
                            InStock = 160,
                            Name = "Onion",
                            Price = 0.60m
                        },
                        new
                        {
                            Id = 18,
                            InStock = 200,
                            Name = "Garlic",
                            Price = 0.40m
                        },
                        new
                        {
                            Id = 19,
                            InStock = 110,
                            Name = "Cucumber",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 20,
                            InStock = 90,
                            Name = "Bell Pepper",
                            Price = 1.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
