// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receipt.WebApi.Data;

#nullable disable

namespace Receipt.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240608161410_update-data-with-descriptive-items ")]
    partial class updatedatawithdescriptiveitems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Receipt.WebApi.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InStock = 50,
                            Name = "Phone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 2,
                            InStock = 30,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 3,
                            InStock = 40,
                            Name = "Tablet",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 4,
                            InStock = 20,
                            Name = "Camera",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 5,
                            InStock = 70,
                            Name = "Headset",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 6,
                            InStock = 100,
                            Name = "Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 7,
                            InStock = 80,
                            Name = "Keyboard",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 8,
                            InStock = 25,
                            Name = "Monitor",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 9,
                            InStock = 15,
                            Name = "Printer",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 10,
                            InStock = 50,
                            Name = "Router",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 11,
                            InStock = 60,
                            Name = "Speaker",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 12,
                            InStock = 150,
                            Name = "Charger",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 13,
                            InStock = 10,
                            Name = "Drone",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 14,
                            InStock = 20,
                            Name = "VR Headset",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 15,
                            InStock = 120,
                            Name = "SSD",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 16,
                            InStock = 90,
                            Name = "HDD",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 17,
                            InStock = 130,
                            Name = "RAM",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 18,
                            InStock = 200,
                            Name = "USB Drive",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 19,
                            InStock = 40,
                            Name = "Smartwatch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 20,
                            InStock = 60,
                            Name = "Fitness Tracker",
                            Price = 99.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
